### ISSUE TITLE
CRAN check problem for at least two packages

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#251]
https://cran.r-project.org/web/checks/check_results_nasapower.html

**Comment by maelle** [comment]
https://cran.r-project.org/web/checks/check_results_rtweet.html

**Comment by llrs** [comment]
rtweet has the same error than reported in #349. So, I think the problem might be more general than just two packages and might be fixed with a new update to vcr in CRAN

**Comment by maelle** [comment]
On GitHub Actions and locally there's a vcr failure for nasapower tests that do not use vcr https://github.com/ropensci/nasapower/actions/runs/3398663485/jobs/5651901782

See also https://github.com/ropensci/nasapower/pull/73#issuecomment-1305210144

**Comment by KevCaz** [comment]
Same error in rcites and rmangal.

**Comment by sckott** [comment]
Thanks @maelle ! I'm aware of the situation. Various issues to fix - already getting help from folks

**Comment by jhnwllr** [comment]
rgbif is still having problems
https://cran.r-project.org/web/checks/check_results_rgbif.html

**Comment by llrs** [comment]
@jhnwllr the issue is not fixed in CRAN yet. Until the fix in vcr is in CRAN or we modify our packages, they will continue failing. Could you check that #252 solves the problem in your local computer ? If it does it is "just" a matter of time to get it merged and in CRAN to prevent this problems

**Comment by bretsw** [comment]
I've been following the various vcr issues threads the past week. I know you all are working on this, so thank you!

I wanted to let you know this also an issue for tidytags; one test throws the same error (https://cran.r-project.org/web/checks/check_results_tidytags.html) as has been reported for the other packages in this thread. 

**My question for more experienced package developers:** (@sckott? @maelle? @llrs?)
I received the "Please correct before 2022-11-20 to safely retain your package on CRAN." email from CRAN. Any advice on how I should respond to them to keep tidytags up on CRAN in the interim?

Again, many thanks!

**Comment by sckott** [comment]
thanks @bretsw for dropping in here. Since I've been in touch with CRAN, and let them know we're working on the fixes, they will probably give more time than the date they gave you, but I'm not 100% sure about that. You could respond and say that it's not a problem with your package and that you've been told a fix is coming that should resolve the check failures.

**Comment by llrs** [comment]
@sckott I already sent an email to CRAN about this situation ~5 days ago pointing to the PR I submitted and got this reply: 
> Thanks. The vcr maintainer promised a fix for some of these problems
soon, so let's wait and hope for the best :-)

@bretsw I hope to submit a new rtweet version to CRAN soon to include some needed improvements. If vcr is not fixed by the 20th, or there isn't any new deadline, I would submit a new version of rtweet skipping all test with vcr in CRAN (if I fix some remaining issues for this release). This way I might avoid rtweet to be removed from CRAN and thus tidytags.

**Comment by jhnwllr** [comment]
Running the dev version of vcr `remotes::install_github("ropensci/vcr")` fixes the test failures for **rgbif**.

**Comment by sckott** [comment]
thanks @llrs for the update

@jhnwllr great, glad it works for you!

**Comment by sckott** [comment]
we're almost ready to submit, closing this issue
